.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. ausbit_qt test_ausbit_qt
clean: FORCE
	$(MAKE) -C .. ausbit_qt_clean test_ausbit_qt_clean
check: FORCE
	$(MAKE) -C .. test_ausbit_qt_check
ausbit-qt ausbit-qt.exe: FORCE
	 $(MAKE) -C .. ausbit_qt
